VARIABLE = 'VARIABLE'
NUMBER = 'NUMBER'
NEWLINE = 'NEWLINE'
OPERATOR = 'OPERATOR'
KEYWORD = 'KEYWORD'
BOOLEAN = 'BOOLEAN'
PRINT = 'PRINT'
COMMA = 'COMMA'

EXCLAMATION_MARK = "!"
ADDITION = '+'
SUBTRACTION = '-'
MULTIPLICATION = '*'
DIVISION = '/'
MODULUS = '%'
EXPONENTIATION = '^'
INCREMENT = '++'
DECREMENT = '--'
LEFT_PARENTHESES = '('
RIGHT_PARENTHESES = ')'
EQUAL = '='


BINARY_OPERATOR = ()
UNARY_OPERATOR = ()

